spring.datasource.url=jdbc:sqlite:lifetracker.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

app.api-token=dev-token-123